local opts = { noremap = true, silent = true }
vim.keymap.set("n", "<S-h>", "<C-w>h", opts)
vim.keymap.set("n", "<S-k>", "<C-w>k", opts)
vim.keymap.set("n", "<S-j>", "<C-w>j", opts)
vim.keymap.set("n", "<S-l>", "<C-w>l", opts)
vim.keymap.set("n", "<S-s>", ":split<Return>", opts)
vim.keymap.set("n", "<S-v>", ":vsplit<Return>", opts)
vim.keymap.set("n", "<S-q>", "<CMD>bd<CR>", opts)
vim.keymap.set("n", "<S-f>", "<CMD>Telescope file_browser path=%:p:h select_buffer=true<CR>", opts)
vim.keymap.set("n", "<S-g>", "<CMD>Telescope live_grep<CR>", opts)
vim.keymap.set("n", "<S-b>", "<CMD>Telescope buffers<CR>", opts)
